version: ~> 1.0
dist: bionic
language: node_js
install:
  - npm ci
script:
  # Test Git hooks in CI, to make sure script upgrades do not break them.
  - npm run prepare
  - ./.git/hooks/pre-commit
  - git log -1 --pretty=%B >> latest.log && ./.git/hooks/commit-msg latest.log
  - npm run test:ci
  - npx commitlint-travis
  - npm pack --loglevel notice 2>&1 >/dev/null | sed -e 's/^npm notice //' && rm *.tgz
branches:
  except:
    - gh-pages
notifications:
  email: false
deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
env:
  global:
    # Permissions: public_repo
    # travis encrypt --pro GH_TOKEN=<value>
    - secure: "eIQAKRKdIOZlfqwmYA1nwCWrpdIaBVc7fDuBp1iPQGTzm2xn/Gtr6HZNN7gHUnHuMC2KfTcz0MXzQrSQzqTn/A/ivMafwGlh7TQe+8KGMAS2yLDSSihD6qlkZQM5pbFppjEx6fxvDoo7VnJO5YoRodzu7tLq/O7Qn3TSyiEE64KQI+vnZBz4q/snjUxxu6cC4X06NGG1ixBy1SQdUYLb/WEyvvzD0cnoJoIFtGio1GuuDjq4PHCECMx5aIop+sndkH+SCZRRcGc6rLPnbunWyYQbR4FJUBwUKzYkc0AtjO2rBScKitfTBom9mcppttOzuTrpcRp8IAGx8ZngJCZinPPwoEvgjqtb5majJo84jwSc4qetOlOQfnWpTnRDMs1KeDvNVk167ROKiBuVA37I0dkC5um4vSxDwJKu50O3dpWHxxgKWNYG6xEew+RJxyh0iUgnFh/ToQGozhKm50EPA2PKuAqT1Qq9b16clNMiCqVuN9Y4B6Uxb/+nf2+gihNQcx/Rl5o9VsRPAw4TnSOVsd7BBAL+i0Krs3/bSF9wpgYd65PmCrDPZdOxdrEu0dULLnTvNufMh1VCA0D6u9Wbt5OyIsISf4cy1q+CmaKakUQOyqAj8fGOxppgk/xgbhuyiOI6HMx0igKqiiuEjklQ7lHt95xstHmU4jN9BX2GBpU="
    # travis encrypt --pro GIT_AUTHOR_NAME=<value>
    - secure: "sZYbsqfWWlN4KY1DeCvZ5G6NIRxg52fZeeXi7O1rBegDNBWtEyFBjWbs6CHu5r3fkayvXzin3XHz9sdJMawortvgo+SiQE3Ni6cBv1wdipx0ztI2T8+NBaoi3uDJ9qXBZ2cKTypqjudHpsc9E37/NOb3U4u4StA7pnGV0uAg98dxy1nblWN4p0NT46bMpkgEc1Gy9yrfJFwoHdI8eBgXsRLRP7G6Iv9Gjk06qZJxyYFjW4NzhxvbsvJxLtryKUP5xYnViTGJTcH9PXK0J3K8ZQT1EV4Kks8U5Nf1ydJNxssRa87Ttf50KcJYhhpratU9UKTJOs6yvuA6UY54ZSrLHVtyWxgBoGifPFqn73N4TpnmcW5SI51o6mfizOzL4yS2NJR7+WnUk8WrBpPYhsHyKZcE94r1X2vNNO5G488tfQiPbM7crr4CZT7un1r9EACVzHZE+IFkStImE0Tzay64bJVOwS/SaHFbnoLHgkDQ6/iioUcIRHugUvt6X+jM+QiemxwiZlwY1J0QSYjFIh8KJRnJ2p3xCDxW2yuKjpH4FSzESQRcQRZ4Hg3uYebW7kakBVJPmxY2rdZAxBDiV/fPJuuvgyNTW+qz7M/GDLwg/K23ucVj1KXcho/GO913rZTxljCbmgQF76ZrG30psSDeRa6p50cMInZD1Aq+aqxGXJE="
    # travis encrypt --pro GIT_AUTHOR_EMAIL=<value>
    - secure: "0nTmfYW4TxxxwFtDE9u4Oez8a/M61k4u8ARGk4JxmEmsGDNk3ADs4EOZlXHzhZ4Bq4EXzE4pSRe4X+loc6agEwAQ7i/0nxUuKUCpu3vsP9TBCYM37MVClSlh7dGLj4oxh62CZfTpyJ7HckL4uouOzjl/YNzfdN6yaXPZhUxaxu2DgVFfT18Evqe5Fp7okJlL2uul/MeHFAsSqADQ/KIE3nSNy5cqLf8tTjrG2FmQmzA9nHG1GggC/DdcaStMpdxSdW/zMLGyt46wkA0y0+TNdUsJ1aSkLYyIJj1Bn/A+ZNpS85VkxIiumYswlT3hBj4jKYpCOoMPKwE4GuRTiaudXcJBwPo6fuXVN+efLf2l7WTN4iYyP2UizZ452gCjGseSvkmg7+tVqJGH3nMTufs9Y/8yJ1wXdhFzaDmQUgAXPEkoOTEdMU+W6aeC/56/1y6W2ZozbAleQgb0LFrfWrB2bI0cASPylHTacsMOf6lWNiZYIoR4alG5EGQ0NyHRD34x9JHqOt3eWB9pM0DXNa91f+26Ze2JfUlGqVNdesJXFbw3Krsgt1TqTyeVcUd9luetcIv1qMRjgZr+1IgQnmtKDNn8xi8FW+c4JwsVcUR2KottVipCCimEzIZ17jykv8JBkIUiEBITyBG8vQBcaaGrX2epyCGQDns9asRS6FFYeo8="
    # travis encrypt --pro NPM_TOKEN=<value>
    - secure: "Skb9tmWf0xu3EUA2doviR2zSaMn3X7F//2yCRDFCS+oxggIaRjWzP4eZYlL6zM55FQwgBgsKk/DRVkcERi8uXDGZhkJJJPEWp+CfjjOHgld2LdDjpD2eWc7Crf8/6d4j6p/wQzh2V9hG6NAvsJXIQMPvGYjwIVC49shgmNJVZJ+euA+k6s8oJOQzpHhFcABDQ24szkRCMPoymQ/ru6QNfY9ZVRWNACMHEONcr0az/nwu0ymReVMmGY1atzUmkqbTRiKCT1GClWHmrlv0N/WxKktU7zMwZqXDlYlDw2+56bq/1q8RnSIV9gkAMVvk47Eq3/JPcwqM5p3HezD1OtKc6izLiI41TV9d7walN1WvV1D53HqOLQOm3IQKrkSbiM1FmQN0GWOaADKCdYa6dX8UCk2CLkcn86wC0mchV1aypu8MAKGusbP4OiL6iZM/owuz/UJdwdNS7OKraB12w7NlOL4jsoZpQxYKOtwIsGg+QsBH4tLILECHlLFcsyBsp0bCL/QQtMaTUFM9mZRKoCYL4Up5jjyIuY4IW0tvvT1CG+TCVoVI79ouZ4vqU6oQ4igDnEUIgd/FSA7blaRi0pU1vF8K6HBJw1pBBBuXgvehZ8ohEMUFDOy6xVjGKtD6/c8JFiFk2d4N+CFxQlqbepC/PK6t+sL8049drzg8HHuZ9Qw="
